export default {
  'formio-tab-panel-active': 'formsflow-current',
  'formio-tab-link-active': 'formsflow-current',
  'formio-tab-link-container-active': 'formsflow-current',
  'sr-only': 'formsflow-sr-only',
  'formio-form-error': 'formsflow-form-group--error',
  'formio-label-error': 'formsflow-label--error',
  'formio-input-success': 'formsflow-input--success',
  'formio-input-error': 'formsflow-input--error',
  'formio-modal-save': 'formsflow-error',
  'formio-alert-danger': 'formsflow-alert formsflow-alert--error formsflow-alert--no-icon',
  'formio-alert-success': 'formsflow-alert formsflow-alert--success formsflow-alert--no-icon',
  'formio-modal-cancel-button': 'formsflow-button formsflow-button--secondary',
  'formio-modal-confirm-button': 'formsflow-button',
  'form-control ui fluid selection dropdown': 'formsflow-select maxw-full',
};
